### ISSUE TITLE
Lines completely left aligned

### ISSUE THREAD

**Issue by tehabe** [aab12345/thelounge-theme-flat-dark#2]
While I really like the theme, I would be suggest also a complete left aligned variant, like it looks when I open The Lounge on my mobile phone.

**Comment by aab12345** [comment]
If you would like to add the code change I can test and authorise it.  I'm not 100% sure what you mean.

**Comment by tehabe** [comment]
Essentially, I want the option to have the mobile view on the desktop, not more, not less.

![IMG_1667](https://github.com/aab12345/thelounge-theme-flat-dark/assets/67130363/ff939989-4f1c-4b54-967d-a3153c2f1365)

**Comment by TehPeGaSuS** [comment]
@tehabe, you can customise TheLounge on the fly using CSS..

[This](https://thelounge.chat/docs/guides/custom-css#no-nick-indentation) may be useful

**Comment by aab12345** [comment]
Yes customise it via css.  I don't want to add that globally.  Thanks
